name: assess
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.3.2
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  linkedin_login: ^2.3.1
  sign_in_with_apple: ^5.0.0
  stacked: ^3.4.0
  stacked_services: ^1.3.0
  logger: ^1.4.0
  json_annotation: ^4.8.0
  device_info_plus: ^9.0.3
  timezone: ^0.9.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.5.1
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true
  assets:
     - asset/
     - asset/images/